### ISSUE TITLE
Fix driver API to work with kernel 5.19+

### ISSUE THREAD

**Issue by joefowler** [usnistgov/quantum-sensors-drivers#15]
**[Original report](https://bitbucket.org/nist_microcal/nist_qsp_drivers/issues/15) by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

Kernel won’t build correctly on linux 5.19.0-41-generic in Ubuntu 22.04. See [this discussion at the kernel mailing list](https://lkml.org/lkml/2022/3/9/1219) where we see the API for `pci_alloc_consistent`, `pci_unmap_sg`, and so on. They were wrappers for other calls, and sometime in early 2022 were removed from the kernel. I assume the wrappers were deprecated, then removed.

* Find the exact kernel version we should test on.
* Replace deprecated calls with the new ones.

‌

**Comment by joefowler** [comment]
**Original comment by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

Compile on kernel 5.19.0-41-generic looks like this:

```text
pcuser@687Feynman-linux:~/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver$ make
make -C /lib/modules/5.19.0-41-generic/build M=/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver modules
make[1]: Entering directory '/usr/src/linux-headers-5.19.0-41-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  CC [M]  /home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.o
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c: In function ‘performance_submit’:
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:512:23: error: implicit declaration of function ‘pci_alloc_consistent’ [-Werror=implicit-function-declaration]
  512 |         buffer_virt = pci_alloc_consistent(lro->pci_dev, size, &buffer_bus);
      |                       ^~~~~~~~~~~~~~~~~~~~
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:512:21: warning: assignment to ‘u8 *’ {aka ‘unsigned char *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  512 |         buffer_virt = pci_alloc_consistent(lro->pci_dev, size, &buffer_bus);
      |                     ^
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c: In function ‘lancero_desc_alloc’:
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:1316:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 1316 |         desc_virt = (struct lancero_desc *)pci_alloc_consistent(dev,
      |                     ^
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c: In function ‘lancero_desc_free’:
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:1456:9: error: implicit declaration of function ‘pci_free_consistent’ [-Werror=implicit-function-declaration]
 1456 |         pci_free_consistent(dev, number * sizeof(struct lancero_desc),
      |         ^~~~~~~~~~~~~~~~~~~
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c: In function ‘free_transfer’:
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:1623:17: error: implicit declaration of function ‘pci_unmap_sg’; did you mean ‘pci_unmap_rom’? [-Werror=implicit-function-declaration]
 1623 |                 pci_unmap_sg(lro->pci_dev, transfer->sgm->sgl, transfer->sgm->mapped_pages,
      |                 ^~~~~~~~~~~~
      |                 pci_unmap_rom
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c: In function ‘create_transfer_user’:
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:1844:31: error: implicit declaration of function ‘pci_map_sg’; did you mean ‘pci_map_rom’? [-Werror=implicit-function-declaration]
 1844 |         transfer->sgl_nents = pci_map_sg(lro->pci_dev, transfer->sgm->sgl,
      |                               ^~~~~~~~~~
      |                               pci_map_rom
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c: In function ‘probe’:
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:2531:19: error: implicit declaration of function ‘pci_set_dma_mask’ [-Werror=implicit-function-declaration]
 2531 |                 (!pci_set_dma_mask(pdev, DMA_BIT_MASK(64)))) {
      |                   ^~~~~~~~~~~~~~~~
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:2537:17: error: implicit declaration of function ‘pci_set_consistent_dma_mask’ [-Werror=implicit-function-declaration]
 2537 |                 pci_set_consistent_dma_mask(pdev, DMA_BIT_MASK(32));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c: In function ‘char_events_read’:
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:2853:9: warning: ignoring return value of ‘copy_to_user’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 2853 |         copy_to_user(buf, &lro->events_irq, 4);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c: In function ‘char_ctrl_write’:
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:2818:9: warning: ignoring return value of ‘copy_from_user’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 2818 |         copy_from_user(&w, buf, 4);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c: In function ‘char_ctrl_read’:
/home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.c:2798:9: warning: ignoring return value of ‘copy_to_user’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 2798 |         copy_to_user(buf, &w, 4);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:257: /home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver/lancero-base.o] Error 1
make[1]: *** [Makefile:1850: /home/pcuser/gitrepos/nist_qsp_drivers/lancero/Lancero-RELEASE/C/driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.19.0-41-generic'
make: *** [Makefile:32: lancero.ko] Error 2
```

‌

**Comment by joefowler** [comment]
**Original comment by Joseph Fowler (Bitbucket: [joe_fowler](https://bitbucket.org/joe_fowler), ).**

----------------------------------------

Fixed by abda79bc
